[project]
name = "claudehandshake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-circuitpython-fingerprint>=2.2.19",
    "pyfingerprint>=1.5",
]
